<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Notifications\Messages\MailMessage;

class ContractNumberGeneratedNotification extends Notification
{
    use Queueable;

    protected $contract;
    protected $contractNumber;
    protected $actor;

    public function __construct($contract, $contractNumber, $actor = null)
    {
        $this->contract = $contract;
        $this->contractNumber = $contractNumber;
        $this->actor = $actor;
    }

    public function via($notifiable)
    {
        return ['database', 'mail'];
    }

    /**
     * 🔥 Dynamic route resolver (STATIC + DYNAMIC workflow safe)
     */
    protected function resolveUrl(): string
    {
        return route(
            $this->contract->contract_type === 'surat'
                ? 'surat.show'
                : 'contracts.show',
            $this->contract
        );
    }

    public function toMail($notifiable)
    {
        $type = $this->contract->contract_type ?? 'contract';
        $url  = $this->resolveUrl();

        $badgeBg   = $type === 'surat' ? '#e6f9f0' : '#e8f1ff';
        $badgeText = $type === 'surat' ? '#0f9d58' : '#2563eb';
        $badgeLabel = strtoupper($type);

        $content = "
        <div style='font-family:Arial,Helvetica,sans-serif;background:#f4f6f9;padding:40px 20px;'>
            <div style='max-width:640px;'>

                <div style='background:#ffffff;padding:32px;border-radius:8px;'>

                    <h2 style='margin:0 0 20px 0;font-size:20px;'>
                        Document Number Generated
                    </h2>

                    <span style='
                        display:inline-block;
                        padding:6px 12px;
                        font-size:12px;
                        font-weight:600;
                        border-radius:20px;
                        background:{$badgeBg};
                        color:{$badgeText};
                        margin-bottom:20px;
                    '>
                        {$badgeLabel}
                    </span>

                    <p>Hello <strong>{$notifiable->nama_user}</strong>,</p>

                    <p>The review process has been completed and a number has been generated for your document.</p>

                    <hr style='border:none;border-top:1px solid #e5e7eb;margin:20px 0;'>

                    <p><strong>Title</strong><br>{$this->contract->title}</p>

                    <p><strong>Document Number</strong><br>
                        <span style='font-family:monospace;font-weight:bold;'>
                            {$this->contractNumber}
                        </span>
                    </p>

                    <p><strong>Generated By</strong><br>" 
                        . ($this->actor->nama_user ?? 'System') . "</p>

                    <p><strong>Date</strong><br>" 
                        . now()->format('d M Y H:i') . "</p>

                    <div style='margin-top:28px;'>
                        <a href='{$url}'
                           style='
                                display:inline-block;
                                padding:10px 18px;
                                background:#111827;
                                color:#ffffff;
                                text-decoration:none;
                                border-radius:6px;
                                font-size:14px;
                           '>
                            View Document
                        </a>
                    </div>

                </div>

                <div style='margin-top:20px;font-size:12px;color:#94a3b8;'>
                    The document is now finalized and ready for use.<br>
                    Legal Management System
                </div>

            </div>
        </div>
        ";

        return (new MailMessage)
            ->subject("[" . strtoupper($type) . "] Document Number Generated - " . $this->contract->title)
            ->view('emails.review-assignment', [
                'content' => $content
            ]);
    }

    public function toArray($notifiable)
    {
        return [
            'type' => 'document_number_generated',
            'title' => 'Document Number Generated',
            'message' => 'Review completed. Document number: ' . $this->contractNumber,
            'contract_id' => $this->contract->id,
            'contract_title' => $this->contract->title,
            'contract_number' => $this->contractNumber,
            'contract_type' => $this->contract->contract_type,
            'generated_by' => $this->actor->nama_user ?? 'System',
            'generated_at' => now()->toDateTimeString(),
            'action_url' => $this->resolveUrl(),
            'icon' => 'fa-check-circle',
            'color' => 'green'
        ];
    }
}